---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ndsg9688/prokarelektronik.com/
    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='node_modules' --exclude='vendor' --exclude='storage' ./ $DEPLOYPATH
